### ISSUE TITLE
Dict examples for ffpe_finder

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#10]
https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/base_function.py#L33-L41

Would be nice to have example of how the dicts could look like

**Comment by Smeds** [comment]
You could add a [doctest](https://docs.python.org/2/library/doctest.html), that would give to a test for the function and a good example.

**Comment by ehugos** [comment]
Example dict for a FFPE artefact: {String_1_Hits: C, String_2_Hits: T}

Example dict for a FFPE-artefact:
        var_dict = "Mutation_Hits": {}, "FFPE_Hits": {"String_1": C, "String_2": T}, "N_Hits": {}, "Del_Hits": {}, 
        "Reference_Support": 0, "Mutation_Support": 0, "FFPE_Support": 1, "N_Support": 0, "Del_Support": 0}
