### ISSUE TITLE
Dict and list examples, mol_count

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#11]
https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/count_function.py#L7-L10

For input it would be nice to have an example of how the dict should look like, but it could maybe be enough if you clarify it in pos_checker since you are referencing it

**Comment by Smeds** [comment]
You could add a [doctest](https://docs.python.org/2/library/doctest.html), that would give to a test for the function and a good example.

**Comment by ehugos** [comment]
Example dict for a FFPE-artefact:
        inp_dict = umi_key: {"Single_Hits": Str1_Hits: {}, Str2_Hits:{C,T}, "Mate_Hits": Mutation_Hits": {},
        "FFPE_Hits": {"String_1": C, "String_2": T}, "N_Hits": {}, "Del_Hits": {}, "Reference_Support": 0,
        "Mutation_Support": 0, "FFPE_Support": 1, "N_Support": 0, "Del_Support": 0}}

 Example list for a FFPE-artefact:
        [0,0,1,0,0]
