### ISSUE TITLE
Dict and list examples, nuc_count

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#12]
https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/count_function.py#L36-L41

For input and output it would be nice to have an example of how the dict and lists should look like, but it could maybe be enough if you clarify it in pos_checker since you are referencing it

**Comment by Smeds** [comment]
You could add a doctest, that would give to a test for the function and a good example.

**Comment by ehugos** [comment]
inp_dict = umi_key: {"Single_Hits": Str1_Hits: {}, Str2_Hits:{C,T}, "Mate_Hits": Mutation_Hits": {},
        "FFPE_Hits": {"String_1": C, "String_2": T}, "N_Hits": {}, "Del_Hits": {}, "Reference_Support": 0,
        "Mutation_Support": 0, "FFPE_Support": 1, "N_Support": 0, "Del_Support": 0}}

Example dict for the nucleotide C for a imaginary input_dict:
        n_sup = {"Paired": {"String_1": {C: {12}}, "String_2": C: {11}, "String_1_Single": C: {5},
        "String_2_Single": C: {2}}
