### ISSUE TITLE
doctest for qrn_ext(read):

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#14]
https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/pos_function.py#L90

Please create a doctest, this would also make it easier to read the code since you can see exactly what is expected as input and what the output will be

**Comment by ehugos** [comment]
Would require that we create a new read only for said purpose, i have instead created a unit-test for this purpose
