### ISSUE TITLE
doctest for hlf_splt(umi_str, char):

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#15]
https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/pos_function.py#L127

Please create a doctest, this would also make it easier to read the code since you can see exactly what is expected as input and what the output will be

**Comment by ehugos** [comment]
>>> hlf_splt("ACTACTAGCTGCTG", "")
    '[ACTACTA, GCTGCTG]'
