### ISSUE TITLE
doctest for cha_splt(umi_str, char):

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#16]
https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/pos_function.py#L114

Please create a doctest, this would also make it easier to read the code since you can see exactly what is expected as input and what the output will be

**Comment by ehugos** [comment]
>>> cha_splt("ACTACTA+GCTGCTG", "+")
    '[ACTACTA, GCTGCTG]'
    >>> cha_splt("ACTACTA_GCTGCTG", "_")
    '[ACTACTA, GCTGCTG]'
