### ISSUE TITLE
Example of output dict for pos_hits(inp_lst, record_pos)

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#18]
Could you please provide an example of the expect output dict

**Comment by ehugos** [comment]
Example dict:
        input_dict = {example_name_UMI_ACTGCA+ACTGCA: {read1, read2}, example_2_name_UMI_TGACGT+TGACGT: {read2}}

Example dict:
        cons_dict = {UMI_tag_1: C, UMI_tag_2: T}
