### ISSUE TITLE
Dual UMI spliting

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#4]
Make it possible to specify how to split dual umi:

1. Split using char, maybe make it possible to specify which char
2. Divide the umi in half, first part is UMI1 and second UMI2

**Comment by ehugos** [comment]
Fixed: 

def qrn_ext(read):
    """ Function for extracting the umi-key, based on the key being present as the last item in the query-name.
    Args:
        :param read: Input bam-read from the umi_dict
    Returns:
        :return: A dict containing the umi-tag
    """
    return read.query_name.split("_")[-1]


def rx_ext(read):
    """ Function for extracting the umi-key, based on the key being present in the RX-tag
    Args:
        :param read: Input bam-read from the umi_dict
    Returns:
        :return: A dict containing the umi-tag
    """
    return str(read.get_tag("RX"))


def cha_splt(umi_str, char):
    """ Split function for the query-name, splits the umi_string based on the split-character argument
        Args:
            :param umi_str: A string representing the umi-tag to be split
            :param char: Character to split the umi-string by
        Returns:
            :return: A dict containing the umi-tag split in two
        """
    return umi_str.split(char)


def hlf_splt(umi_str, char):
    """ Split function for splitting the umi-tag in half based on half its length
    Args:
        :param umi_str: A string representing the umi-tag to be split
        :param char: Not used in this function, however needs to be supplemented as the function call for the query-name
        based split function requires a split character
    Returns:
        :return: A dict containing the umi-tag split in two
    """
    return umi_str[:len(umi_str) // 2], umi_str[len(umi_str) // 2:]
