### ISSUE TITLE
Code simplification

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#5]
https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/fumic.py#L60

change from
`
    res_data = pos_function.pos_checker(bam_lst, n_pos, n_alt, n_ref, ffpe_b, ext_fun, spl_fun, spl_cha)
    mpd_data = res_data[0]
    unmpd_data = res_data[1]
`
to
`
    mpd_data, unmpd_data = pos_function.pos_checker(bam_lst, n_pos, n_alt, n_ref, ffpe_b, `

same for line 71

**Comment by ehugos** [comment]
Great fix, and i fully agree
