### ISSUE TITLE
Make code more readable

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#6]
https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/fumic.py#L68

`
n_cop.samples[sample]['UMI'] = str(mpd_inf[0][0]) + ";" + str(mpd_inf[0][1]) + ";" + str(mpd_inf[0][2]) + \
                                           ";" + str(mpd_inf[0][3]) + ";" + str(mpd_inf[0][4]) + ";" + mpd_inf[1] + \
                                           ";" + mpd_inf[2] + ";" + mpd_inf[3] + ";" + mpd_inf[4]
`

could you use string formatting with naming to make it more easy to read?

Ex
`
'Coordinates: {latitude}, {longitude}'.format(latitude='37.24N', longitude='-115.81W')
`

**Comment by ehugos** [comment]
Solved!

n_cop = "{No_Mutation};{True_Mutation};{FFPE_Artefact};{Unknown};{Deletion}{Ref_Paired;{Var_Paired;" \
                "{Ref_Single};{Var_Single}".format(No_Mutation=mpd_inf[0][0], True_Mutation=mpd_inf[0][1],
                                                   FFPE_Artefact=mpd_inf[0][2], Unknown=mpd_inf[0][3],
                                                   Deletion=mpd_inf[0][4], Ref_Paired=mpd_inf[1],
                                                   Var_Paired=mpd_inf[2], Ref_Single=mpd_inf[3],
                                                   Var_Single=mpd_inf[4])
