### ISSUE TITLE
Dict structure for inf_builder

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#7]
https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/fumic.py#L85

Could be good to have an example of the input dict structure 

also what one can find the output, i.e what's stored at each index position.

**Comment by Smeds** [comment]
You could add a [doctest](https://docs.python.org/2/library/doctest.html), that would give to a test for the function and a good example.

**Comment by ehugos** [comment]
Uses the output from pos_checker to generate a list containing strings representing the data found for each
    record, more specifically support for each variant-type, as well as the support for the reference and variant
    call for str1 and str2.
    The inp_dict is meant to be output from the var_extract function,and is divided into two dicts named
    Single Hits and Mate Hits. The Single-dict contains the molecular support for the reference genome nucleotide
    and the variant nucleotide based on all reads without a mate.
    The Mate-Hits dicts instead contains data regarding the variant-classification, the support for each variant type,
    and the molecular support for the reference genome nucleotide and the variant nucleotide based on reads with a mate.
