### ISSUE TITLE
Comment change

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#8]
https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/base_function.py#L14

One could maybe just write that a base will always be return in plus strand instead of 

> returns the reverse complement for any reverse strand

**Comment by ehugos** [comment]
# Full length with soft clips is required for the index selection to be correct, nucleotides are always returned
        # as they would be on the plus strand
