### ISSUE TITLE
Remove print statements

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/fumic#9]
https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/base_function.py#L91-L95

https://github.com/clinical-genomics-uppsala/fumic/blob/e8ff3e3d82b21552aa6be2084ae3ff222964dc7c/base_function.py#L98-L102

remove print statements or swap to a logger.debug to make it configurable when to print the rows

**Comment by ehugos** [comment]
Done, this was only for testing so that the code worked
